parameters:
#    ac_inst3_media.example.class: AltCloud\Instance3MediaAdminBundle\Example

services:
#    ac_inst3_media.example:
#        class: %ac_inst3_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
