admin_format:
    pattern:  /
    defaults: { _controller: "ACInst3MediaAdminBundle:Format:index" }

admin_format_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACInst3MediaAdminBundle:Format:show" }

admin_format_new:
    pattern:  /new
    defaults: { _controller: "ACInst3MediaAdminBundle:Format:new" }

admin_format_create:
    pattern:  /create
    defaults: { _controller: "ACInst3MediaAdminBundle:Format:create" }
    requirements: { _method: post }

admin_format_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACInst3MediaAdminBundle:Format:edit" }

admin_format_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACInst3MediaAdminBundle:Format:update" }
    requirements: { _method: post }

admin_format_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACInst3MediaAdminBundle:Format:delete" }
    requirements: { _method: post }
