admin_media:
    pattern:  /
    defaults: { _controller: "ACInst3MediaAdminBundle:Media:index" }

admin_media_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACInst3MediaAdminBundle:Media:show" }

admin_media_new:
    pattern:  /new
    defaults: { _controller: "ACInst3MediaAdminBundle:Media:new" }

admin_media_create:
    pattern:  /create
    defaults: { _controller: "ACInst3MediaAdminBundle:Media:create" }
    requirements: { _method: post }

admin_media_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACInst3MediaAdminBundle:Media:edit" }

admin_media_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACInst3MediaAdminBundle:Media:update" }
    requirements: { _method: post }

admin_media_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACInst3MediaAdminBundle:Media:delete" }
    requirements: { _method: post }
